export const ACTION_TYPE = {
	SET_USER: 'SET_USER',
	LOGOUT: 'LOGOUT',

	SET_ROOM_DATA: 'SET_ROOM_DATA',

	ADD_FAVORITE: 'ADD_FAVORITE',
	REMOVE_FAVORITE: 'REMOVE_FAVORITE',
	LOAD_FAVORITES: 'LOAD_FAVORITES',

	SET_SEARCH_PARAMS: 'SET_SEARCH_PARAMS',

	ADD_BOOKING: 'ADD_BOOKING',
};
