export const ACTION_TYPE = {
	SET_USER: 'SET_USER',
	LOGOUT: 'LOGOUT',

	SET_ROOM_DATA: 'SET_ROOM_DATA',
	ADD_REVIEW: 'ADD_REVIEW',
	REMOVE_REVIEW: 'REMOVE_REVIEW',

	ADD_FAVORITE: 'ADD_FAVORITE',
	REMOVE_FAVORITE: 'REMOVE_FAVORITE',
	TOGGLE_FAVORITE: 'TOGGLE_FAVORITE',
	LOAD_FAVORITES: 'LOAD_FAVORITES',

	SET_SEARCH_PARAMS: 'SET_SEARCH_PARAMS',

	ADD_BOOKING: 'ADD_BOOKING',
	REMOVE_BOOKING: 'REMOVE_BOOKING',
	SET_USER_BOOKINGS: 'SET_USER_BOOKINGS',
	SET_ALL_BOOKINGS: 'SET_ALL_BOOKINGS',
};
